# Generated by Django 3.1.2 on 2020-10-24 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('user', '0002_auto_20201024_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='groups',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='auth.group'),
        ),
    ]
