# Generated by Django 3.1.2 on 2020-12-01 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_user_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='meta',
            field=models.JSONField(default=dict),
        ),
    ]
